"""Preflop range helpers ported from the imported poker-range-analyzer project."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Literal, Optional, Sequence

from pokereval.card import Card as PokerEvalCard


Position = Literal["UTG", "MP", "CO", "BTN", "SB", "BB"]
POSITIONS: tuple[Position, ...] = ("UTG", "MP", "CO", "BTN", "SB", "BB")
RANK_LABELS = {
    2: "2",
    3: "3",
    4: "4",
    5: "5",
    6: "6",
    7: "7",
    8: "8",
    9: "9",
    10: "T",
    11: "J",
    12: "Q",
    13: "K",
    14: "A",
}


@dataclass(frozen=True)
class RangeAction:
    """Opening/defense frequencies for a starting hand."""

    raise_frequency: int = 0
    call_frequency: int = 0
    fold_frequency: int = 100

    @property
    def playable_frequency(self) -> int:
        return self.raise_frequency + self.call_frequency


def _action(raise_frequency: int, call_frequency: int = 0, fold_frequency: int = 0) -> RangeAction:
    return RangeAction(
        raise_frequency=raise_frequency,
        call_frequency=call_frequency,
        fold_frequency=fold_frequency,
    )


RANGES: dict[Position, dict[str, RangeAction]] = {
    "UTG": {
        "AA": _action(100),
        "KK": _action(100),
        "QQ": _action(100),
        "JJ": _action(100),
        "TT": _action(100),
        "99": _action(100),
        "88": _action(100),
        "77": _action(100),
        "66": _action(50, fold_frequency=50),
        "55": _action(25, fold_frequency=75),
        "AKs": _action(100),
        "AQs": _action(100),
        "AJs": _action(100),
        "ATs": _action(100),
        "KQs": _action(100),
        "KJs": _action(100),
        "KTs": _action(75, fold_frequency=25),
        "QJs": _action(100),
        "QTs": _action(50, fold_frequency=50),
        "JTs": _action(100),
        "A9s": _action(50, fold_frequency=50),
        "A8s": _action(25, fold_frequency=75),
        "A5s": _action(50, fold_frequency=50),
        "A4s": _action(25, fold_frequency=75),
        "AKo": _action(100),
        "AQo": _action(100),
        "AJo": _action(100),
        "ATo": _action(50, fold_frequency=50),
        "KQo": _action(75, fold_frequency=25),
    },
    "MP": {
        "AA": _action(100),
        "KK": _action(100),
        "QQ": _action(100),
        "JJ": _action(100),
        "TT": _action(100),
        "99": _action(100),
        "88": _action(100),
        "77": _action(100),
        "66": _action(75, fold_frequency=25),
        "55": _action(50, fold_frequency=50),
        "44": _action(25, fold_frequency=75),
        "AKs": _action(100),
        "AQs": _action(100),
        "AJs": _action(100),
        "ATs": _action(100),
        "A9s": _action(75, fold_frequency=25),
        "A8s": _action(50, fold_frequency=50),
        "A5s": _action(75, fold_frequency=25),
        "A4s": _action(50, fold_frequency=50),
        "A3s": _action(25, fold_frequency=75),
        "KQs": _action(100),
        "KJs": _action(100),
        "KTs": _action(100),
        "K9s": _action(25, fold_frequency=75),
        "QJs": _action(100),
        "QTs": _action(75, fold_frequency=25),
        "Q9s": _action(25, fold_frequency=75),
        "JTs": _action(100),
        "J9s": _action(25, fold_frequency=75),
        "T9s": _action(50, fold_frequency=50),
        "AKo": _action(100),
        "AQo": _action(100),
        "AJo": _action(100),
        "ATo": _action(75, fold_frequency=25),
        "KQo": _action(100),
        "KJo": _action(50, fold_frequency=50),
        "QJo": _action(25, fold_frequency=75),
    },
    "CO": {
        "AA": _action(100),
        "KK": _action(100),
        "QQ": _action(100),
        "JJ": _action(100),
        "TT": _action(100),
        "99": _action(100),
        "88": _action(100),
        "77": _action(100),
        "66": _action(100),
        "55": _action(100),
        "44": _action(75, fold_frequency=25),
        "33": _action(50, fold_frequency=50),
        "22": _action(50, fold_frequency=50),
        "AKs": _action(100),
        "AQs": _action(100),
        "AJs": _action(100),
        "ATs": _action(100),
        "A9s": _action(100),
        "A8s": _action(100),
        "A7s": _action(100),
        "A6s": _action(100),
        "A5s": _action(100),
        "A4s": _action(100),
        "A3s": _action(100),
        "A2s": _action(75, fold_frequency=25),
        "KQs": _action(100),
        "KJs": _action(100),
        "KTs": _action(100),
        "K9s": _action(100),
        "K8s": _action(50, fold_frequency=50),
        "K7s": _action(25, fold_frequency=75),
        "QJs": _action(100),
        "QTs": _action(100),
        "Q9s": _action(100),
        "Q8s": _action(50, fold_frequency=50),
        "JTs": _action(100),
        "J9s": _action(100),
        "J8s": _action(50, fold_frequency=50),
        "T9s": _action(100),
        "T8s": _action(75, fold_frequency=25),
        "98s": _action(100),
        "97s": _action(50, fold_frequency=50),
        "87s": _action(100),
        "86s": _action(50, fold_frequency=50),
        "76s": _action(100),
        "75s": _action(25, fold_frequency=75),
        "65s": _action(75, fold_frequency=25),
        "54s": _action(50, fold_frequency=50),
        "AKo": _action(100),
        "AQo": _action(100),
        "AJo": _action(100),
        "ATo": _action(100),
        "A9o": _action(75, fold_frequency=25),
        "A8o": _action(50, fold_frequency=50),
        "A7o": _action(25, fold_frequency=75),
        "KQo": _action(100),
        "KJo": _action(100),
        "KTo": _action(75, fold_frequency=25),
        "QJo": _action(100),
        "QTo": _action(50, fold_frequency=50),
        "JTo": _action(75, fold_frequency=25),
    },
    "BTN": {
        "AA": _action(100),
        "KK": _action(100),
        "QQ": _action(100),
        "JJ": _action(100),
        "TT": _action(100),
        "99": _action(100),
        "88": _action(100),
        "77": _action(100),
        "66": _action(100),
        "55": _action(100),
        "44": _action(100),
        "33": _action(100),
        "22": _action(100),
        "AKs": _action(100),
        "AQs": _action(100),
        "AJs": _action(100),
        "ATs": _action(100),
        "A9s": _action(100),
        "A8s": _action(100),
        "A7s": _action(100),
        "A6s": _action(100),
        "A5s": _action(100),
        "A4s": _action(100),
        "A3s": _action(100),
        "A2s": _action(100),
        "KQs": _action(100),
        "KJs": _action(100),
        "KTs": _action(100),
        "K9s": _action(100),
        "K8s": _action(100),
        "K7s": _action(100),
        "K6s": _action(100),
        "K5s": _action(100),
        "K4s": _action(75, fold_frequency=25),
        "K3s": _action(75, fold_frequency=25),
        "K2s": _action(50, fold_frequency=50),
        "QJs": _action(100),
        "QTs": _action(100),
        "Q9s": _action(100),
        "Q8s": _action(100),
        "Q7s": _action(75, fold_frequency=25),
        "Q6s": _action(75, fold_frequency=25),
        "Q5s": _action(50, fold_frequency=50),
        "Q4s": _action(50, fold_frequency=50),
        "JTs": _action(100),
        "J9s": _action(100),
        "J8s": _action(100),
        "J7s": _action(75, fold_frequency=25),
        "J6s": _action(50, fold_frequency=50),
        "T9s": _action(100),
        "T8s": _action(100),
        "T7s": _action(75, fold_frequency=25),
        "98s": _action(100),
        "97s": _action(100),
        "96s": _action(75, fold_frequency=25),
        "87s": _action(100),
        "86s": _action(100),
        "85s": _action(50, fold_frequency=50),
        "76s": _action(100),
        "75s": _action(100),
        "74s": _action(50, fold_frequency=50),
        "65s": _action(100),
        "64s": _action(75, fold_frequency=25),
        "54s": _action(100),
        "53s": _action(75, fold_frequency=25),
        "43s": _action(75, fold_frequency=25),
        "32s": _action(50, fold_frequency=50),
        "AKo": _action(100),
        "AQo": _action(100),
        "AJo": _action(100),
        "ATo": _action(100),
        "A9o": _action(100),
        "A8o": _action(100),
        "A7o": _action(100),
        "A6o": _action(100),
        "A5o": _action(100),
        "A4o": _action(100),
        "A3o": _action(75, fold_frequency=25),
        "A2o": _action(75, fold_frequency=25),
        "KQo": _action(100),
        "KJo": _action(100),
        "KTo": _action(100),
        "K9o": _action(100),
        "K8o": _action(75, fold_frequency=25),
        "K7o": _action(50, fold_frequency=50),
        "QJo": _action(100),
        "QTo": _action(100),
        "Q9o": _action(100),
        "Q8o": _action(50, fold_frequency=50),
        "JTo": _action(100),
        "J9o": _action(100),
        "J8o": _action(50, fold_frequency=50),
        "T9o": _action(100),
        "T8o": _action(75, fold_frequency=25),
        "98o": _action(100),
        "97o": _action(50, fold_frequency=50),
        "87o": _action(100),
        "76o": _action(75, fold_frequency=25),
        "65o": _action(50, fold_frequency=50),
    },
    "SB": {
        "AA": _action(100),
        "KK": _action(100),
        "QQ": _action(100),
        "JJ": _action(100),
        "TT": _action(100),
        "99": _action(100),
        "88": _action(100),
        "77": _action(100),
        "66": _action(100),
        "55": _action(100),
        "44": _action(100),
        "33": _action(100),
        "22": _action(100),
        "AKs": _action(100),
        "AQs": _action(100),
        "AJs": _action(100),
        "ATs": _action(100),
        "A9s": _action(100),
        "A8s": _action(100),
        "A7s": _action(100),
        "A6s": _action(100),
        "A5s": _action(100),
        "A4s": _action(100),
        "A3s": _action(100),
        "A2s": _action(100),
        "KQs": _action(100),
        "KJs": _action(100),
        "KTs": _action(100),
        "K9s": _action(100),
        "K8s": _action(100),
        "K7s": _action(100),
        "K6s": _action(100),
        "K5s": _action(100),
        "K4s": _action(100),
        "K3s": _action(100),
        "K2s": _action(100),
        "QJs": _action(100),
        "QTs": _action(100),
        "Q9s": _action(100),
        "Q8s": _action(100),
        "Q7s": _action(100),
        "Q6s": _action(100),
        "Q5s": _action(75, fold_frequency=25),
        "Q4s": _action(75, fold_frequency=25),
        "Q3s": _action(50, fold_frequency=50),
        "Q2s": _action(50, fold_frequency=50),
        "JTs": _action(100),
        "J9s": _action(100),
        "J8s": _action(100),
        "J7s": _action(100),
        "J6s": _action(75, fold_frequency=25),
        "J5s": _action(50, fold_frequency=50),
        "T9s": _action(100),
        "T8s": _action(100),
        "T7s": _action(100),
        "T6s": _action(50, fold_frequency=50),
        "98s": _action(100),
        "97s": _action(100),
        "96s": _action(75, fold_frequency=25),
        "87s": _action(100),
        "86s": _action(100),
        "85s": _action(75, fold_frequency=25),
        "76s": _action(100),
        "75s": _action(100),
        "65s": _action(100),
        "64s": _action(100),
        "54s": _action(100),
        "53s": _action(75, fold_frequency=25),
        "43s": _action(75, fold_frequency=25),
        "AKo": _action(100),
        "AQo": _action(100),
        "AJo": _action(100),
        "ATo": _action(100),
        "A9o": _action(100),
        "A8o": _action(100),
        "A7o": _action(100),
        "A6o": _action(100),
        "A5o": _action(100),
        "A4o": _action(100),
        "A3o": _action(100),
        "A2o": _action(100),
        "KQo": _action(100),
        "KJo": _action(100),
        "KTo": _action(100),
        "K9o": _action(100),
        "K8o": _action(100),
        "K7o": _action(75, fold_frequency=25),
        "K6o": _action(75, fold_frequency=25),
        "K5o": _action(50, fold_frequency=50),
        "QJo": _action(100),
        "QTo": _action(100),
        "Q9o": _action(100),
        "Q8o": _action(75, fold_frequency=25),
        "JTo": _action(100),
        "J9o": _action(100),
        "J8o": _action(75, fold_frequency=25),
        "T9o": _action(100),
        "T8o": _action(75, fold_frequency=25),
        "98o": _action(100),
        "87o": _action(100),
        "76o": _action(75, fold_frequency=25),
        "65o": _action(75, fold_frequency=25),
    },
    "BB": {
        "AA": _action(100),
        "KK": _action(100),
        "QQ": _action(100),
        "JJ": _action(75, call_frequency=25),
        "TT": _action(50, call_frequency=50),
        "99": _action(25, call_frequency=75),
        "88": _action(25, call_frequency=75),
        "77": _action(0, call_frequency=100),
        "66": _action(0, call_frequency=100),
        "55": _action(0, call_frequency=100),
        "44": _action(0, call_frequency=100),
        "33": _action(0, call_frequency=100),
        "22": _action(0, call_frequency=100),
        "AKs": _action(75, call_frequency=25),
        "AQs": _action(50, call_frequency=50),
        "AJs": _action(50, call_frequency=50),
        "ATs": _action(25, call_frequency=75),
        "A9s": _action(25, call_frequency=75),
        "A8s": _action(25, call_frequency=75),
        "A7s": _action(25, call_frequency=75),
        "A6s": _action(25, call_frequency=75),
        "A5s": _action(50, call_frequency=50),
        "A4s": _action(50, call_frequency=50),
        "A3s": _action(25, call_frequency=75),
        "A2s": _action(25, call_frequency=75),
        "KQs": _action(50, call_frequency=50),
        "KJs": _action(25, call_frequency=75),
        "KTs": _action(25, call_frequency=75),
        "K9s": _action(0, call_frequency=100),
        "K8s": _action(0, call_frequency=100),
        "K7s": _action(0, call_frequency=100),
        "K6s": _action(0, call_frequency=100),
        "K5s": _action(0, call_frequency=100),
        "K4s": _action(0, call_frequency=100),
        "K3s": _action(0, call_frequency=100),
        "K2s": _action(0, call_frequency=100),
        "QJs": _action(25, call_frequency=75),
        "QTs": _action(25, call_frequency=75),
        "Q9s": _action(0, call_frequency=100),
        "Q8s": _action(0, call_frequency=100),
        "Q7s": _action(0, call_frequency=100),
        "Q6s": _action(0, call_frequency=100),
        "Q5s": _action(0, call_frequency=100),
        "Q4s": _action(0, call_frequency=100),
        "Q3s": _action(0, call_frequency=75, fold_frequency=25),
        "Q2s": _action(0, call_frequency=75, fold_frequency=25),
        "JTs": _action(25, call_frequency=75),
        "J9s": _action(0, call_frequency=100),
        "J8s": _action(0, call_frequency=100),
        "J7s": _action(0, call_frequency=100),
        "J6s": _action(0, call_frequency=75, fold_frequency=25),
        "J5s": _action(0, call_frequency=75, fold_frequency=25),
        "J4s": _action(0, call_frequency=50, fold_frequency=50),
        "T9s": _action(25, call_frequency=75),
        "T8s": _action(0, call_frequency=100),
        "T7s": _action(0, call_frequency=100),
        "T6s": _action(0, call_frequency=75, fold_frequency=25),
        "98s": _action(25, call_frequency=75),
        "97s": _action(0, call_frequency=100),
        "96s": _action(0, call_frequency=100),
        "95s": _action(0, call_frequency=50, fold_frequency=50),
        "87s": _action(25, call_frequency=75),
        "86s": _action(0, call_frequency=100),
        "85s": _action(0, call_frequency=75, fold_frequency=25),
        "76s": _action(25, call_frequency=75),
        "75s": _action(0, call_frequency=100),
        "74s": _action(0, call_frequency=50, fold_frequency=50),
        "65s": _action(25, call_frequency=75),
        "64s": _action(0, call_frequency=100),
        "54s": _action(25, call_frequency=75),
        "53s": _action(0, call_frequency=100),
        "43s": _action(0, call_frequency=100),
        "42s": _action(0, call_frequency=50, fold_frequency=50),
        "32s": _action(0, call_frequency=75, fold_frequency=25),
        "AKo": _action(75, call_frequency=25),
        "AQo": _action(50, call_frequency=50),
        "AJo": _action(25, call_frequency=75),
        "ATo": _action(0, call_frequency=100),
        "A9o": _action(0, call_frequency=100),
        "A8o": _action(0, call_frequency=100),
        "A7o": _action(0, call_frequency=100),
        "A6o": _action(0, call_frequency=100),
        "A5o": _action(0, call_frequency=100),
        "A4o": _action(0, call_frequency=100),
        "A3o": _action(0, call_frequency=100),
        "A2o": _action(0, call_frequency=100),
        "KQo": _action(25, call_frequency=75),
        "KJo": _action(0, call_frequency=100),
        "KTo": _action(0, call_frequency=100),
        "K9o": _action(0, call_frequency=100),
        "K8o": _action(0, call_frequency=75, fold_frequency=25),
        "K7o": _action(0, call_frequency=75, fold_frequency=25),
        "K6o": _action(0, call_frequency=50, fold_frequency=50),
        "K5o": _action(0, call_frequency=50, fold_frequency=50),
        "K4o": _action(0, call_frequency=50, fold_frequency=50),
        "K3o": _action(0, call_frequency=25, fold_frequency=75),
        "K2o": _action(0, call_frequency=25, fold_frequency=75),
        "QJo": _action(0, call_frequency=100),
        "QTo": _action(0, call_frequency=100),
        "Q9o": _action(0, call_frequency=100),
        "Q8o": _action(0, call_frequency=75, fold_frequency=25),
        "Q7o": _action(0, call_frequency=50, fold_frequency=50),
        "Q6o": _action(0, call_frequency=50, fold_frequency=50),
        "JTo": _action(0, call_frequency=100),
        "J9o": _action(0, call_frequency=100),
        "J8o": _action(0, call_frequency=75, fold_frequency=25),
        "J7o": _action(0, call_frequency=50, fold_frequency=50),
        "T9o": _action(0, call_frequency=100),
        "T8o": _action(0, call_frequency=100),
        "T7o": _action(0, call_frequency=50, fold_frequency=50),
        "98o": _action(0, call_frequency=100),
        "97o": _action(0, call_frequency=75, fold_frequency=25),
        "87o": _action(0, call_frequency=100),
        "86o": _action(0, call_frequency=75, fold_frequency=25),
        "76o": _action(0, call_frequency=100),
        "75o": _action(0, call_frequency=50, fold_frequency=50),
        "65o": _action(0, call_frequency=100),
        "64o": _action(0, call_frequency=50, fold_frequency=50),
        "54o": _action(0, call_frequency=100),
        "53o": _action(0, call_frequency=50, fold_frequency=50),
        "43o": _action(0, call_frequency=50, fold_frequency=50),
    },
}


def classify_hole_cards(cards: Sequence[PokerEvalCard]) -> Optional[str]:
    """Return compact poker notation such as ``AKs``, ``AQo`` or ``TT``."""

    if len(cards) != 2 or any(card is None for card in cards):
        return None
    if any(not hasattr(card, "rank") or not hasattr(card, "suit") for card in cards):
        return None

    left, right = cards
    left_rank = int(left.rank)
    right_rank = int(right.rank)
    if left_rank not in RANK_LABELS or right_rank not in RANK_LABELS:
        return None

    ranks = sorted((left_rank, right_rank), reverse=True)
    high, low = ranks
    high_label = RANK_LABELS[high]
    low_label = RANK_LABELS[low]
    if high == low:
        return f"{high_label}{low_label}"
    suffix = "s" if int(left.suit) == int(right.suit) else "o"
    return f"{high_label}{low_label}{suffix}"


def get_hand_action(position: str, hand: str) -> RangeAction:
    """Return range action for ``hand`` at ``position``, defaulting to fold."""

    normalized = normalize_position(position)
    if normalized is None:
        return RangeAction()
    return RANGES[normalized].get(hand, RangeAction())


def is_hand_in_range(position: str, hand: str) -> bool:
    return get_hand_action(position, hand).playable_frequency > 0


def get_range_percentage(position: str) -> float:
    """Return approximate percentage of all 1326 combos played by a range."""

    normalized = normalize_position(position)
    if normalized is None:
        return 0.0

    combo_count = 0.0
    for hand, action in RANGES[normalized].items():
        combo_count += _hand_combo_count(hand) * (action.playable_frequency / 100.0)
    return (combo_count / 1326.0) * 100.0


def normalize_position(position: object) -> Optional[Position]:
    text = str(position or "").strip().upper()
    aliases = {
        "BUTTON": "BTN",
        "DEALER": "BTN",
        "CUTOFF": "CO",
        "SMALL_BLIND": "SB",
        "BIG_BLIND": "BB",
    }
    text = aliases.get(text, text)
    return text if text in POSITIONS else None


def _hand_combo_count(hand: str) -> int:
    if len(hand) == 2:
        return 6
    if hand.endswith("s"):
        return 4
    return 12


__all__ = [
    "POSITIONS",
    "Position",
    "RANGES",
    "RangeAction",
    "classify_hole_cards",
    "get_hand_action",
    "get_range_percentage",
    "is_hand_in_range",
    "normalize_position",
]
